"""Robust torch-autograd pose and sparse-structure optimization."""

from __future__ import annotations

from dataclasses import dataclass

import torch
from torch import Tensor

from .camera import Camera
from .frame import CORNER, EDGELET
from .geometry import invert_transform, se3_exp, transform_points


def huber_weights(residual_norm: Tensor, delta: float, eps: float = 1e-9) -> Tensor:
    """IRLS weights for a vector-valued Huber loss."""

    return torch.where(
        residual_norm <= delta,
        torch.ones_like(residual_norm),
        delta / residual_norm.clamp_min(eps),
    )


@dataclass(slots=True)
class PoseOptimizationResult:
    T_world_cam: Tensor
    inliers: Tensor
    residuals: Tensor
    iterations: int
    converged: bool
    initial_error: float
    final_error: float


class PoseOptimizer:
    """Minimize image-plane reprojection error with left-multiplicative SE(3).

    Jacobians are generated by PyTorch autograd, which keeps all supported
    camera models on one implementation path and makes this module useful as a
    correctness reference for future analytic/CUDA kernels.
    """

    def __init__(
        self,
        camera: Camera,
        *,
        max_iterations: int = 10,
        huber_delta: float = 2.0,
        outlier_threshold: float = 2.0,
        damping: float = 1e-6,
        min_points: int = 6,
    ) -> None:
        self.camera = camera
        self.max_iterations = max_iterations
        self.huber_delta = huber_delta
        self.outlier_threshold = outlier_threshold
        self.damping = damping
        self.min_points = min_points

    def optimize(
        self,
        T_world_cam: Tensor,
        points_world: Tensor,
        pixels_observed: Tensor,
        valid: Tensor | None = None,
        *,
        kinds: Tensor | None = None,
        levels: Tensor | None = None,
        gradients: Tensor | None = None,
    ) -> PoseOptimizationResult:
        """Refine a camera pose from sparse geometric observations.

        Metadata is optional so the original all-corner, level-zero API remains
        unchanged. Edgelet residuals are constrained only along their image
        gradient. Pyramid levels express measurement uncertainty in level
        coordinates, matching SVO's pose-optimization convention.
        """

        if points_world.ndim != 2 or points_world.shape[1] != 3:
            raise ValueError("points_world must have shape [N, 3]")
        if not points_world.is_floating_point():
            raise TypeError("points_world must be floating point")
        count = points_world.shape[0]
        if pixels_observed.shape != (count, 2):
            raise ValueError("pixels_observed must have shape [N, 2]")
        if not pixels_observed.is_floating_point():
            raise TypeError("pixels_observed must be floating point")
        if valid is None:
            valid = torch.ones(count, dtype=torch.bool, device=points_world.device)
        elif valid.shape != (count,) or valid.dtype != torch.bool:
            raise ValueError("valid must be a boolean tensor with shape [N]")
        else:
            valid = valid.to(device=points_world.device)

        if kinds is None:
            kinds = torch.full((count,), CORNER, dtype=torch.long, device=points_world.device)
        elif kinds.shape != (count,):
            raise ValueError("kinds must have shape [N]")
        else:
            kinds = kinds.to(device=points_world.device, dtype=torch.long)
        if bool(((kinds != CORNER) & (kinds != EDGELET)).any()):
            raise ValueError("kinds may contain only CORNER or EDGELET")

        if levels is None:
            levels = torch.zeros(count, dtype=torch.long, device=points_world.device)
        elif levels.shape != (count,):
            raise ValueError("levels must have shape [N]")
        elif levels.dtype.is_floating_point or levels.dtype == torch.bool:
            raise TypeError("levels must use an integer dtype")
        else:
            levels = levels.to(device=points_world.device, dtype=torch.long)
        if bool((levels < 0).any()):
            raise ValueError("levels must be non-negative")

        if gradients is None:
            if bool((kinds == EDGELET).any()):
                raise ValueError("gradients are required for edgelet observations")
            gradients = torch.zeros(
                (count, 2), device=points_world.device, dtype=points_world.dtype
            )
            gradients[:, 0] = 1.0
        elif gradients.shape != (count, 2):
            raise ValueError("gradients must have shape [N, 2]")
        else:
            gradients = gradients.to(device=points_world.device, dtype=points_world.dtype)
        gradient_norm = torch.linalg.vector_norm(gradients, dim=-1, keepdim=True)
        usable_gradient = torch.isfinite(gradients).all(dim=-1) & (
            gradient_norm.squeeze(-1) > torch.finfo(points_world.dtype).eps
        )
        if bool(((kinds == EDGELET) & ~usable_gradient).any()):
            raise ValueError("edgelet gradients must be finite and non-zero")
        fallback_gradient = torch.zeros_like(gradients)
        fallback_gradient[:, 0] = 1.0
        gradients = torch.where(
            usable_gradient[:, None],
            gradients / gradient_norm.clamp_min(torch.finfo(points_world.dtype).eps),
            fallback_gradient,
        )

        T_cam_world = invert_transform(T_world_cam).detach().clone()
        points = points_world[valid]
        observed = pixels_observed[valid]
        feature_kinds = kinds[valid]
        feature_levels = levels[valid]
        feature_gradients = gradients[valid]
        source_indices = torch.nonzero(valid, as_tuple=False).squeeze(-1)

        if points.shape[0] < self.min_points:
            residuals = torch.full(
                (points_world.shape[0],),
                float("inf"),
                device=points_world.device,
                dtype=points_world.dtype,
            )
            return PoseOptimizationResult(
                T_world_cam=T_world_cam,
                inliers=torch.zeros_like(valid),
                residuals=residuals,
                iterations=0,
                converged=False,
                initial_error=float("inf"),
                final_error=float("inf"),
            )

        level_scale = torch.pow(
            torch.full_like(feature_levels, 2, dtype=points.dtype),
            feature_levels,
        )
        is_edgelet = feature_kinds == EDGELET
        edgelet_sigma = torch.where(
            is_edgelet,
            torch.full_like(level_scale, 2.0),
            torch.ones_like(level_scale),
        )

        def residuals_and_visibility(transform: Tensor) -> tuple[Tensor, Tensor, Tensor]:
            points_cam = transform_points(transform, points)
            projected, visible = self.camera.project(points_cam)
            raw_residuals = projected - observed
            edgelet_error = (raw_residuals * feature_gradients).sum(dim=-1, keepdim=True)
            edgelet_residuals = edgelet_error * feature_gradients
            semantic_residuals = torch.where(is_edgelet[:, None], edgelet_residuals, raw_residuals)
            geometric_residuals = semantic_residuals / level_scale[:, None]
            optimization_residuals = geometric_residuals / edgelet_sigma[:, None]
            visible = (
                visible
                & torch.isfinite(geometric_residuals).all(dim=-1)
                & torch.isfinite(optimization_residuals).all(dim=-1)
            )
            return optimization_residuals, geometric_residuals, visible

        def robust_cost(norms: Tensor) -> Tensor:
            return torch.where(
                norms <= self.huber_delta,
                0.5 * norms.square(),
                self.huber_delta * (norms - 0.5 * self.huber_delta),
            ).mean()

        initial_vector, initial_geometric, initial_visible = residuals_and_visibility(T_cam_world)
        if int(initial_visible.sum()) < self.min_points:
            residuals = torch.full(
                (points_world.shape[0],),
                float("inf"),
                device=points_world.device,
                dtype=points_world.dtype,
            )
            return PoseOptimizationResult(
                T_world_cam=T_world_cam,
                inliers=torch.zeros_like(valid),
                residuals=residuals,
                iterations=0,
                converged=False,
                initial_error=float("inf"),
                final_error=float("inf"),
            )
        initial_norms = torch.linalg.vector_norm(initial_vector, dim=-1)
        initial_geometric_norms = torch.linalg.vector_norm(initial_geometric, dim=-1)
        initial_error = float(initial_geometric_norms[initial_visible].median().detach().cpu())
        initial_cost = robust_cost(initial_norms[initial_visible]).detach()
        best_transform = T_cam_world.clone()
        best_cost = initial_cost
        converged = False
        completed_iterations = 0

        for iteration in range(self.max_iterations):

            def project_with_delta(delta: Tensor, base_transform: Tensor = T_cam_world) -> Tensor:
                candidate = se3_exp(delta) @ base_transform
                residuals, _, _ = residuals_and_visibility(candidate)
                return residuals

            zero = torch.zeros(6, device=points.device, dtype=points.dtype, requires_grad=True)
            residual_vector = project_with_delta(zero)
            _, _, visible = residuals_and_visibility(T_cam_world)
            active = visible & torch.isfinite(residual_vector).all(dim=-1)
            if int(active.sum()) < self.min_points:
                break

            # [N, 2, 6]. vectorize is substantially faster for typical SVO maps.
            jacobian = torch.autograd.functional.jacobian(
                project_with_delta,
                zero,
                create_graph=False,
                vectorize=True,
            )
            residual_vector = residual_vector.detach()[active]
            jacobian = jacobian.detach()[active]
            norms = torch.linalg.vector_norm(residual_vector, dim=-1)
            sqrt_weight = huber_weights(norms, self.huber_delta).sqrt()[:, None, None]
            weighted_jacobian = (jacobian * sqrt_weight).reshape(-1, 6)
            weighted_residual = (residual_vector * sqrt_weight.squeeze(-1)).reshape(-1)
            hessian = weighted_jacobian.T @ weighted_jacobian
            gradient = weighted_jacobian.T @ weighted_residual
            diagonal_scale = torch.diagonal(hessian).mean().clamp_min(1.0)
            hessian = hessian + self.damping * diagonal_scale * torch.eye(
                6, device=hessian.device, dtype=hessian.dtype
            )
            try:
                update = -torch.linalg.solve(hessian, gradient)
            except torch.linalg.LinAlgError:
                break
            if not torch.isfinite(update).all():
                break

            current_full, _, current_visible = residuals_and_visibility(T_cam_world)
            accepted_transform: Tensor | None = None
            accepted_cost: Tensor | None = None
            accepted_update = update
            # Backtracking prevents an unconstrained GN step from corrupting a
            # good motion prior. Costs are compared on points visible in both
            # states so leaving the image cannot masquerade as improvement.
            for _ in range(7):
                candidate = (se3_exp(accepted_update) @ T_cam_world).detach()
                candidate_full, _, candidate_visible = residuals_and_visibility(candidate)
                common = current_visible & candidate_visible
                if int(common.sum()) >= self.min_points:
                    current_norms = torch.linalg.vector_norm(current_full[common], dim=-1)
                    candidate_norms = torch.linalg.vector_norm(candidate_full[common], dim=-1)
                    current_cost = robust_cost(current_norms)
                    candidate_cost = robust_cost(candidate_norms)
                    if torch.isfinite(candidate_cost) and candidate_cost <= current_cost:
                        accepted_transform = candidate
                        accepted_cost = candidate_cost.detach()
                        break
                accepted_update = accepted_update * 0.5
            if accepted_transform is None or accepted_cost is None:
                break
            T_cam_world = accepted_transform
            completed_iterations = iteration + 1
            if accepted_cost < best_cost:
                best_cost = accepted_cost
                best_transform = T_cam_world.clone()
            if torch.linalg.vector_norm(accepted_update) < 1e-6:
                converged = True
                break

        T_cam_world = best_transform
        _, final_geometric, visible = residuals_and_visibility(T_cam_world)
        final_norms = torch.linalg.vector_norm(final_geometric, dim=-1)
        local_inliers = (
            visible & torch.isfinite(final_norms) & (final_norms <= self.outlier_threshold)
        )

        residuals = torch.full(
            (points_world.shape[0],),
            float("inf"),
            device=points_world.device,
            dtype=points_world.dtype,
        )
        residuals[source_indices] = final_norms
        inliers = torch.zeros(points_world.shape[0], dtype=torch.bool, device=points_world.device)
        inliers[source_indices] = local_inliers
        finite_final = final_norms[visible & torch.isfinite(final_norms)]
        final_error = (
            float(finite_final.median().detach().cpu()) if finite_final.numel() else float("inf")
        )
        return PoseOptimizationResult(
            T_world_cam=invert_transform(T_cam_world),
            inliers=inliers,
            residuals=residuals,
            iterations=completed_iterations,
            converged=converged or (completed_iterations > 0 and bool(best_cost <= initial_cost)),
            initial_error=initial_error,
            final_error=final_error,
        )


def optimize_point(
    point_world: Tensor,
    poses_world_cam: Tensor,
    pixels: Tensor,
    cameras: list[Camera],
    *,
    max_iterations: int = 5,
    huber_delta: float = 2.0,
) -> Tensor:
    """Refine one landmark observed by multiple camera poses."""

    if point_world.shape != (3,):
        raise ValueError("point_world must have shape [3]")
    if poses_world_cam.ndim != 3 or poses_world_cam.shape[1:] != (4, 4):
        raise ValueError("poses_world_cam must have shape [N, 4, 4]")
    if pixels.ndim != 2 or pixels.shape[1] != 2:
        raise ValueError("pixels must have shape [N, 2]")
    if poses_world_cam.shape[0] != pixels.shape[0] or len(cameras) != pixels.shape[0]:
        raise ValueError("one pose and camera are required for every observation")
    if not point_world.is_floating_point():
        raise TypeError("point_world must be floating point")

    estimate = point_world.detach().clone()
    if not torch.isfinite(estimate).all() or not cameras:
        return estimate

    # The landmark tensor controls placement and precision. Pose and pixel
    # observations are constants during structure refinement, so normalizing
    # them here also avoids mixed-device failures deep in the projection path.
    poses = poses_world_cam.detach().to(estimate)
    observed = pixels.detach().to(estimate)
    finite_observations = torch.isfinite(poses).all(dim=(-2, -1)) & torch.isfinite(observed).all(
        dim=-1
    )
    candidate_indices = torch.nonzero(finite_observations, as_tuple=False).squeeze(-1)
    if candidate_indices.numel() < 2:
        return estimate

    def evaluate(point: Tensor, indices: Tensor) -> tuple[Tensor, Tensor]:
        residual_parts: list[Tensor] = []
        visibility_parts: list[Tensor] = []
        for index_tensor in indices:
            index = int(index_tensor)
            point_cam = transform_points(invert_transform(poses[index]), point[None])[0]
            projection, camera_visible = cameras[index].project(point_cam[None])
            residual = projection[0] - observed[index]
            residual_parts.append(residual)
            visibility_parts.append(
                camera_visible.reshape(-1)[0]
                & torch.isfinite(point_cam).all()
                & torch.isfinite(residual).all()
            )
        return torch.stack(residual_parts), torch.stack(visibility_parts)

    def robust_cost(norms: Tensor) -> Tensor:
        return torch.where(
            norms <= huber_delta,
            0.5 * norms.square(),
            huber_delta * (norms - 0.5 * huber_delta),
        ).mean()

    for _ in range(max_iterations):
        _, candidate_visibility = evaluate(estimate, candidate_indices)
        active_indices = candidate_indices[candidate_visibility]
        # A single image observation cannot constrain landmark depth.
        if active_indices.numel() < 2:
            break

        variable = estimate.detach().requires_grad_(True)

        def residual_fn(point: Tensor, observation_indices: Tensor = active_indices) -> Tensor:
            residuals, _ = evaluate(point, observation_indices)
            return residuals

        residual = residual_fn(variable)
        jacobian = torch.autograd.functional.jacobian(residual_fn, variable, vectorize=True)
        if not torch.isfinite(residual).all() or not torch.isfinite(jacobian).all():
            break
        norms = torch.linalg.vector_norm(residual.detach(), dim=-1)
        sqrt_weight = huber_weights(norms, huber_delta).sqrt()[:, None, None]
        j = (jacobian.detach() * sqrt_weight).reshape(-1, 3)
        r = (residual.detach() * sqrt_weight.squeeze(-1)).reshape(-1)
        hessian = j.T @ j
        diagonal_scale = torch.diagonal(hessian).mean().clamp_min(1.0)
        hessian = hessian + 1e-6 * diagonal_scale * torch.eye(3, device=j.device, dtype=j.dtype)
        try:
            update = -torch.linalg.solve(hessian, j.T @ r)
        except torch.linalg.LinAlgError:
            break
        if not torch.isfinite(update).all():
            break

        current_cost = robust_cost(norms).detach()
        accepted_estimate: Tensor | None = None
        accepted_update = update
        # A candidate must keep every active observation valid. Otherwise a
        # point could lower its apparent cost simply by moving behind a camera
        # or outside its image. Backtracking also protects against a nonlinear
        # Gauss-Newton step increasing the robust reprojection objective.
        for _ in range(10):
            candidate = (estimate + accepted_update).detach()
            candidate_residual, candidate_visible = evaluate(candidate, active_indices)
            if bool(candidate_visible.all()):
                candidate_norms = torch.linalg.vector_norm(candidate_residual, dim=-1)
                candidate_cost = robust_cost(candidate_norms)
                if torch.isfinite(candidate_cost) and candidate_cost <= current_cost:
                    accepted_estimate = candidate
                    break
            accepted_update = accepted_update * 0.5

        if accepted_estimate is None:
            break
        estimate = accepted_estimate
        if torch.linalg.vector_norm(accepted_update) < 1e-6:
            break
    return estimate.detach()
